"""Generate the installed-skills catalog from the live Hermes server.

Usage (as module): awesomeskills.catalog.main(hermes=None) -> writes references/
"""
from __future__ import annotations
from pathlib import Path
import json
import os
import sys


def _scan_skills(base: Path) -> tuple[int, dict, int]:
    """Return (count, profiles_map, plugin_count)."""
    default_skills = 0
    profiles: dict[str, int] = {}
    plugins = 0
    if base.exists():
        default_skills = len(list(base.glob("skills/**/SKILL.md")))
        for prof in base.glob("profiles/*"):
            if prof.is_dir():
                profiles[prof.name] = len(list(prof.glob("skills/**/SKILL.md")))
    # plugins: hermes-agent plugins + profile plugins
    for pat in ("hermes-agent/plugins", "plugins"):
        plugins += len(list(base.glob(f"{pat}/*")))
    for prof in base.glob("profiles/*"):
        plugins += len(list((prof / "hermes-agent/plugins").glob("*"))) if (prof / "hermes-agent/plugins").exists() else 0
    return default_skills, profiles, plugins


def main(hermes: str | None = None) -> int:
    base = Path(hermes).expanduser() if hermes else Path("~/.hermes").expanduser()
    default_skills, profiles, plugin_count = _scan_skills(base)

    cat = []
    cat.append("# Hermes Installed Catalog\n")
    cat.append(f"- **Skills (default profile):** {default_skills}")
    cat.append(f"- **Plugins:** {plugin_count}")
    cat.append(f"- **Profiles:** {', '.join(profiles) or 'default only'}")
    cat.append("")
    cat.append("_Generated by `awesomeskills catalog`. Re-run after installing skills._\n")

    ref_dir = Path(__file__).resolve().parent.parent.parent.parent.parent / "skills" / "github" / "hermes-installed-catalog" / "references"
    # Fallback: alongside package if not inside the repo layout
    if not ref_dir.exists():
        ref_dir = Path.cwd() / "references"
    ref_dir.mkdir(parents=True, exist_ok=True)
    (ref_dir / "installed-inventory.md").write_text("\n".join(cat) + "\n", encoding="utf-8")
    meta = {"skills_default": default_skills, "profiles": profiles,
            "plugins": plugin_count, "hermes_home": str(base)}
    (ref_dir / "installed.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"Catalogo gerado: skills={default_skills} plugins={plugin_count} profiles={len(profiles)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
